name: Input Varibles

on:
  workflow_dispatch:
    inputs:
      number1:
        description: "Number One"
        type: number

      number2:
        description: "Number Two"
        type: number

jobs:
  sum:
    name: Sum
    runs-on: ubuntu-latest
    steps:
      - name: Count
        id: sum
        run: |
          sum=$(( ${{ inputs.number1 }} + ${{ inputs.number2 }} ))
          echo "sum=$sum" >> "$GITHUB_OUTPUT"

      - name: Result
        run: echo "${{inputs.number1}} ${{inputs.number2}} = ${{steps.sum.outputs.sum}}"
