name: uv yml

on:
    pull_request:
        branches:
            - main
        
        paths:
            - 'uv/**'
            - '.github/workflows/uv_two.yml'

jobs:
    uv_two:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run uv_two script
              run: |
                echo "Running uv_two script..."
                # Add your script commands here